[package]
name = "azure-storage-cli"
version = "0.5.1"
description = "A CLI to interact with Azure Storage services"
edition = "2021"
license = "MIT"
authors = ["bcaswell@gmail.com"]
repository = "https://github.com/demoray/azure-storage-cli"
keywords = ["azure", "blobs"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.79"
azure_core = {version="0.18", features=["tokio-fs"]}
azure_data_tables = "0.18.1"
azure_identity = "0.18.1"
azure_storage = "0.18"
azure_storage_blobs = "0.18"
azure_storage_datalake = "0.18"
azure_storage_queues = "0.18"
clap = {version="4.4", default-features=false, features=["std", "help", "usage", "error-context", "suggestions", "derive", "env"]}
env_logger = "0.10"
futures = "0.3"
log = "0.4"
native-tls = { version = "0.2.11", features = ["vendored"] }
parse_duration = "2.1.1"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
time = { version = "0.3.31", features = ["parsing"] }
tokio = {version="1.35", features=["macros", "rt-multi-thread", "io-util", "io-std"]}
uuid = { version = "1.6", features = ["v4", "serde"] }

[[bin]]
path = "src/main.rs"
name = "azs"

[profile.release]
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
