[package]
name = "azure-storage-blob-client"
version = "0.1.0"
description = "Azure Blob Storage Client"
edition = "2021"
license = "MIT"
authors = ["bcaswell@gmail.com"]
keywords = ["azure", "blobs"]

[dependencies]
anyhow = "1.0.75"
azure_core = {version="0.17", features=["tokio-fs"]}
azure_storage = "0.17"
azure_storage_blobs = "0.17"
clap = {version="4.0", default-features=false, features=["std", "help", "usage", "error-context", "suggestions", "derive", "env"]}
env_logger = "0.10"
futures = "0.3"
log = "0.4"
tokio = {version="1.34", features=["macros", "rt-multi-thread", "io-util", "io-std"]}
uuid = { version = "1.0", features = ["v4", "serde"] }
