name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  STORAGE_ACCOUNT: STORAGE_ACCOUNT_NAME
  STORAGE_ACCESS_KEY: STORAGE_ACCESS_KEY

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: eng/build.sh
