name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  STORAGE_ACCOUNT: STORAGE_ACCOUNT_NAME
  STORAGE_ACCESS_KEY: STORAGE_ACCESS_KEY

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - os: macos-latest
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-latest
          target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - uses: Swatinem/rust-cache@v2
    - run: eng/build.sh ${{ matrix.target }}
      shell: bash
    - uses: actions/upload-artifact@v3.1.3
      if: matrix.os == 'windows-latest'
      with:
        name: ${{ matrix.build }}
        path: target/${{ matrix.target }}/release/azs.exe
    - uses: actions/upload-artifact@v3.1.3
      if: matrix.os != 'windows-latest'
      with:
        name: ${{ matrix.build }}
        path: target/${{ matrix.target }}/release/azs